services:
  relay:
    build: .
    image: unquestionify-relay:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    environment:
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
